# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 66fd52c
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: nichelle.sequeira@epfl.ch
author_name: Nichelle Sequeira
github_org: nichellesequeira
package_name: protavision
project_name: ProtaVision
short_description: This project is part of the Practical Programming in Chemistry
    course given at EPFL (spring semester 2024), with aim to familiriaze ourselves
    with using GitHub and collaborating on a programming project together.
